version: '3.9'

# TODO: remove internet access

services:
  cnc:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    hostname: cnc.mirai-lab
    container_name: mirai_lab_cnc
    networks:
      shared:
        ipv4_address: 10.1.1.2
    command: /bin/bash -c "/bin/bash /home/cnc/entrypoint.sh && /bin/bash" # setup mysql
  
  attacker:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_attacker
    networks:
      shared:
        ipv4_address: 10.1.1.3
  
  scanner:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_scanner
    networks:
      shared:
        ipv4_address: 10.1.1.11
    command: /bin/bash -c "/bin/bash /home/build/scanListen && /bin/bash" # start scanner
  
  bot0:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_0
    networks:
      shared:
        ipv4_address: 10.1.1.10
    #command: /bin/bash -c "/bin/bash /home/bot/entrypoint.sh && /bin/bash" # download and run

  bot1:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_1
    networks:
      shared:
        ipv4_address: 10.1.1.11

  bot2:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_2
    networks:
      shared:
        ipv4_address: 10.1.1.12

  bot4:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_3
    networks:
      shared:
        ipv4_address: 10.1.1.13

networks:
  shared:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"
  default:
    internal: true