version: '3.9'

# TODO: remove internet access

services:
  cnc:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    domainname: mirai.cnc.lab
    container_name: mirai_lab_cnc
    networks:
      shared:
        ipv4_address: 10.1.1.2
    entrypoint: "apt install sl"

  bot:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot
    networks:
      shared:
        ipv4_address: 10.1.1.3

networks:
  shared:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"
  default:
    internal: true