version: '3.9'

services:
  cnc:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    hostname: cnc.mirai-lab
    container_name: mirai_lab_cnc
    networks:
      shared:
        ipv4_address: 10.1.1.2
    command: /bin/bash -c "/bin/bash /home/cnc/entrypoint.sh && /bin/bash" # setup mysql
  
  attacker:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_attacker
    hostname: attacker
    networks:
      shared:
        ipv4_address: 10.1.1.3
    
  victim:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_victim
    hostname: victim
    networks:
      shared:
        ipv4_address: 10.1.1.5
    command: /bin/bash -c "/etc/init.d/apache2 start && /bin/bash"
    
  bot0:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_0
    hostname: bot0
    networks:
      shared:
        ipv4_address: 10.1.1.10
    #command: /bin/bash -c "/home/debug/mirai.dbg"

  bot1:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_1
    hostname: bot1
    networks:
      shared:
        ipv4_address: 10.1.1.11
    command: /bin/bash -c "/bin/bash /home/bot/entrypoint.sh && /bin/bash"

  bot2:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_2
    hostname: bot2
    networks:
      shared:
        ipv4_address: 10.1.1.12
    command: /bin/bash -c "/bin/bash /home/bot/entrypoint.sh && /bin/bash"

  bot3:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot_3
    hostname: bot3
    networks:
      shared:
        ipv4_address: 10.1.1.13
    command: /bin/bash -c "/bin/bash /home/bot/entrypoint.sh && /bin/bash"

networks:
  shared:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"
  default:
    internal: true
