version: '3.9'

# TODO: remove internet access

services:
  cnc:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    hostname: cnc.mirai-lab
    container_name: mirai_lab_cnc
    networks:
      shared:
        ipv4_address: 10.1.1.2
    command: /bin/bash -c "/bin/bash /home/cnc/entrypoint.sh && /bin/bash" # setup mysql

  bot:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_bot
    networks:
      shared:
        ipv4_address: 10.1.1.3
  
  attacker:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: mirai_lab
    container_name: mirai_lab_attacker
    networks:
      shared:
        ipv4_address: 10.1.1.4

networks:
  shared:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"
  default:
    internal: true